name: furniture_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0 #It help us to use SVG on our app dont use 0.18.*
  google_fonts: ^1.1.0 # We can use any fonts from google fonts
  http: ^0.12.2 # It help us to  fatch data from API
  animated_text_kit: ^2.2.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  modal_progress_hud: ^0.1.3
  localize_and_translate: ^3.0.2
  google_sign_in: ^4.5.1
#  flutter_bloc: ^2.1.1
  cached_network_image: ^2.3.2+1
  font_awesome_flutter: ^8.8.1



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/cart.svg
    - assets/icons/payment.svg
    - assets/icons/help.svg
    - assets/icons/language.svg
    - assets/ripple.gif
    - assets/spinner.gif
    - assets/logos/google.jpg
    - assets/logos/smartphone.jpg
    - assets/langs/en.json
    - assets/langs/ar.json




  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf


